
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3000:3000"
    env_file:
      - ./email-server/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
